"""update schema

Revision ID: 315ccaa70477
Revises: 
Create Date: 2026-03-09 22:09:29.367244

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '315ccaa70477'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CUSTOMERS', schema=None) as batch_op:
        batch_op.add_column(sa.Column('USER_ID', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['USER_ID'], ['id'])

    with op.batch_alter_table('MESSAGES', schema=None) as batch_op:
        batch_op.add_column(sa.Column('USER_ID', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('SUBJECT', sa.String(length=200), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['USER_ID'], ['id'])

    with op.batch_alter_table('MESSAGES_RECIPIENTS', schema=None) as batch_op:
        batch_op.add_column(sa.Column('STATUS', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('SENT_AT', sa.DateTime(), nullable=True))
        batch_op.alter_column('MESSAGE_ID',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('CUSTOMER_ID',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('MESSAGES_RECIPIENTS_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('MESSAGES_RECIPIENTS_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'MESSAGES', ['MESSAGE_ID'], ['ID'])
        batch_op.create_foreign_key(None, 'CUSTOMERS', ['CUSTOMER_ID'], ['ID'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('MESSAGES_RECIPIENTS', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('MESSAGES_RECIPIENTS_ibfk_2'), 'CUSTOMERS', ['CUSTOMER_ID'], ['ID'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('MESSAGES_RECIPIENTS_ibfk_1'), 'MESSAGES', ['MESSAGE_ID'], ['ID'], ondelete='CASCADE')
        batch_op.alter_column('CUSTOMER_ID',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('MESSAGE_ID',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('SENT_AT')
        batch_op.drop_column('STATUS')

    with op.batch_alter_table('MESSAGES', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('SUBJECT')
        batch_op.drop_column('USER_ID')

    with op.batch_alter_table('CUSTOMERS', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('USER_ID')

    # ### end Alembic commands ###
