"""org_id nullable, remove user_id from customers

Revision ID: e5a8db030b0b
Revises: 315ccaa70477
Create Date: 2026-03-22 16:28:38.584617

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e5a8db030b0b'
down_revision = '315ccaa70477'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('invite_code', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_code')
    )
    with op.batch_alter_table('CUSTOMERS', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('CUSTOMERS_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'organizations', ['org_id'], ['id'])
        batch_op.drop_column('USER_ID')

    with op.batch_alter_table('MESSAGES_RECIPIENTS', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('MESSAGES_RECIPIENTS_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('MESSAGES_RECIPIENTS_ibfk_1'), type_='foreignkey')
        batch_op.alter_column('MESSAGE_ID',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('CUSTOMER_ID',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'MESSAGES', ['MESSAGE_ID'], ['ID'])
        batch_op.create_foreign_key(None, 'CUSTOMERS', ['CUSTOMER_ID'], ['ID'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'organizations', ['org_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('role')
        batch_op.drop_column('org_id')

    with op.batch_alter_table('MESSAGES_RECIPIENTS', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('MESSAGES_RECIPIENTS_ibfk_1'), 'MESSAGES', ['MESSAGE_ID'], ['ID'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('MESSAGES_RECIPIENTS_ibfk_2'), 'CUSTOMERS', ['CUSTOMER_ID'], ['ID'], ondelete='CASCADE')
        batch_op.alter_column('CUSTOMER_ID',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('MESSAGE_ID',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('CUSTOMERS', schema=None) as batch_op:
        batch_op.add_column(sa.Column('USER_ID', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('CUSTOMERS_ibfk_1'), 'users', ['USER_ID'], ['id'])
        batch_op.drop_column('org_id')

    op.drop_table('organizations')
    # ### end Alembic commands ###
